# LTactic — Système Tactique de Reconnaissance & Cyberdéfense
# Armée de Terre — Légion étrangère
# Auteur : ADC VOISSION Patrice

github: [teremuhamblin]

# Liens institutionnels officiels pour le soutien, les partenariats,
# le mécénat, les contacts civilo-militaires et les projets numériques.
custom:
  - https://www.defense.gouv.fr/terre
  - https://www.defense.gouv.fr/terre/contacts
  - https://www.defense.gouv.fr/ema/civilo-militaire
  - https://www.defense.gouv.fr/reserve
  - https://www.defense.gouv.fr/terre/actualites
  - https://www.defense.gouv.fr/terre/organisation
